### PR TITLE
Revert "Revert "Stacktemplateshare""

### PR DESCRIPTION
**Pull request by hakankaradis**
Reverts koding/koding#9658
http://recordit.co/l8xb7786uA

### CODE REVIEW

**Comment by gokmen** [comment]
@hakankaradis there was an issue that allowing users to unshare team default stack. and the menu on sidebar after share with team clicked was not getting updated until reload. can u take a screencast for this scenario as well?

**Comment by hakankaradis** [comment]
@gokmen Here is the screencast. http://recordit.co/9qXRj8JpY5
For the first problem I added this check https://github.com/koding/koding/pull/9688/files#diff-9a1d2088b1f40f120f91ef72a6694adbR172
Second problem was about the updating store correctly, https://github.com/koding/koding/pull/9688/files#diff-8aae516a858445e847c6ed695880bbc1R1039

**Review by gokmen — APPROVED** [review]

**Comment by gokmen** [comment]
it LGTM but let's wait for next production deploy.

**Comment by gokmen** [comment]
ping @hakankaradis

**Review by gokmen — APPROVED** [review]

**Pull request merged**
