### PR TITLE
Unused total var removed to keep code clean

### PR DESCRIPTION
**Pull request by d6o**
## Description
In both string representations functions a total var was being created to represent the sum of volumes/objects but this var isn't used anywhere and already exists a function who returns this same total, so i removed to keep code clean.

## Motivation and Context
This keep the code clean and doesn't allocate unnecessary machine resources

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gokmen** [comment]
Probably we are not using this cleaner code anymore but your changes LGTM 👍  cc/ @rjeczalik

**Review by gokmen — APPROVED** [review]

**Comment by rjeczalik** [comment]
The idea back then was to display it at the end as a summary.

Actually the multiinstances cleaner is a leftover after solo, so effectively it is a dead code and can be removed altogether.

@DiSiqueira Would you do that, remove the tool?

**Comment by DiSiqueira** [comment]
Not sure if i understand your comment @rjeczalik, should i delete this file?

**Comment by rjeczalik** [comment]
@DiSiqueira I meant you can remove whole koding/kites/kloud/cleaners directory and remove cmd/cleaner from go/build.sh script.

**Comment by DiSiqueira** [comment]
@rjeczalik Folder deleted and file modified, this is what are you expecting? Let me know if any other change are necessary.

**Comment by rjeczalik** [comment]
@DiSiqueira I'm going to give it a try and merge it afterwards.

**Comment by DiSiqueira** [comment]
Do you want me to edit this PR updating those changes or it is better to keep it as history??

**Comment by rjeczalik** [comment]
@DiSiqueira We have not preference for squashing commits, it can stay as is as far as I'm concerned.

**Comment by rjeczalik** [comment]
Superseded by #10545.

**Pull request closed without merging**
