### PR TITLE
Searchbar style

### PR DESCRIPTION
**Pull request by drewsetski**
## Description
Changed all styles according to design from [Invision - IDE Searchfind Updates ](https://projects.invisionapp.com/d/main#/projects/prototypes/10118425)

## Video:
https://www.dropbox.com/s/l55gck4myeyrjg7/OpsWay7%20-%C2%A0Koding%20_%20IDE%20-%20Google%20Chrome%2001.05.2017%2011_52_50.mp4?dl=0

### Word selection
selection
### Search
search
### Search and replace
search-replace
### Search options
search-options
### Search and replace smaller
search-replace-smaller
### Search and replace the smallest
search-replace-smallest
### Search in all files
search-in-all-files
### Search in all files - Not found
search-in-all-files-not-found
### Find file by name
find-file-by-name
### Goto line
goto-line

### CODE REVIEW

**Comment by hakankaradis** [comment]
@ftasdelen ping

**Comment by ftasdelen** [comment]
The only thing i see is "Find by file name" interface should include black transparent shade at the background covering the whole page except sidebar.

image

Other then that, TGTM.

**Comment by drewsetski** [comment]
Hello everyone! I've added overlay to file finder. And for now all other searchbar views close, when we open one of them.
image

**Comment by hakankaradis** [comment]
closing this pr, reopened here #11133

**Pull request closed without merging**
