### PR TITLE
koding: switch to go1.7.1

### PR DESCRIPTION
**Pull request by rjeczalik**
/cc @cihangir

### CODE REVIEW

**Comment by cihangir** [comment]
https://github.com/koding/infra/pull/5

**Comment by rjeczalik** [comment]
@szkl gentle ping

**Comment by rjeczalik** [comment]
@cihangir @szkl gentle ping

**Comment by cihangir** [comment]
i was waiting for deployment of current master before merging this, but it has been so long since the inception of this PR, so merged with squash ( sorry for your commits ) in case we  may need to revert it for an emergency 


Thanks a lot for the upgrade! You 🚀

**Comment by rjeczalik** [comment]
Thanks!

**Pull request merged**
