### PR TITLE
Resource state modal: design updates

### PR DESCRIPTION
**Pull request by alex-ionochkin**
@gokmen, @ftasdelen, here is the PR with the latest design revisions of resource state modal. Could you please review it?

Demos:
http://recordit.co/U2E3aBbUqI
http://recordit.co/FEIuuZpcKm

https://github.com/koding/koding/issues/8452

### CODE REVIEW

**Comment by gokmen** [comment]
@alex-ionochkin this looks good to me, but can we make the transition between build to installing software steps seamless? in the first screencast afais there is a gap between those steps which makes the output view hidden for a second which is not looking good.

**Comment by alex-ionochkin** [comment]
You're right, we can improve that behaviour - http://recordit.co/IL1YXfUZiC

**Comment by gokmen** [comment]
@alex-ionochkin this LGTM restarted tests fyi.

@ftasdelen @sinan can u guys check it out as well?

**Comment by ftasdelen** [comment]
I got a small design update on the second step. Removed the boxes and added a separator line between credentials and requirements.

https://drive.google.com/open?id=0B2MBJBlRnx3xdmdDNXZPWWJHV2M
https://drive.google.com/open?id=0B2MBJBlRnx3xTnRZQ09JeXdrRHc

cc @alex-ionochkin @sinan

**Comment by sinan** [comment]
thx @alex-ionochkin. a design improvement is necessary please consult to @ftasdelen

**Comment by alex-ionochkin** [comment]
PR has been updated with new design improvements - http://recordit.co/GlcIybQT44

**Comment by alex-ionochkin** [comment]
@sinan, @ftasdelen, can you take a look one more time?

**Comment by gokmen** [comment]
@alex-ionochkin there was a request for animating the alien between page transitions cc/ @sinan

**Comment by sinan** [comment]
thx @alex-ionochkin, @gokmen https://github.com/koding/koding/pull/8679#issuecomment-237274647 can be done in another pr, no need to make this wait.

**Pull request merged**
