### PR TITLE
Remove 'Migrate from Solo' Wizard

### PR DESCRIPTION
**Pull request by usirin**
Since we don't have solo anymore, we don't need a migrator app. 
## Motivation and Context

Completes #8705
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My change requires a change to the documentation. (Do we need to update koding docs? /cc @kwagdy)
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by gokmen** [comment]
@kwagdy can u update koding docs and remove migration related ones once this deployed?

**Comment by gokmen** [comment]
@usirin I was going to merge but it seems CI didn't trigger, not seeing any tests cc/ @szkl

**Comment by usirin** [comment]
@szkl any ideas how we can trigger a build for this PR?

**Comment by usirin** [comment]
I am merging this as it passed the tests.

**Comment by usirin** [comment]
@szkl thanks for triggering the build btw.

**Pull request merged**
