### PR TITLE
StackTemplate: build over social api

### PR DESCRIPTION
**Pull request by gokmen**
## Kloud methods exposed over social api
image

`JStackTemplate::build` endpoint now passes `payload` data as flatten key/value pair with prefixed as `payload_` and can be accessible in stack templates, I've created following sample stack template for showing usage of `payload` data and it also has GitHub Status API support which updates individual pushes to have updated build status on GitHub.

You can see the whole flow in this screencast: http://quick.as/glofbbya

```yaml

provider:
  digitalocean:
    access_token: '${var.digitalocean_access_token}'

variable:
  github_status:
    default: |-
      # GitHub Status API:
      GH_POST () {
        curl "https://api.github.com/repos/$REPO/statuses/$COMMIT_ID?access_token=$APITOKEN" \
          -H "Content-Type: application/json" \
          -X POST \
          -d "{\"state\": \"$1\", \"context\":\"Test Build on Koding\" ,\"description\": \"Koding\", \"target_url\": \"$TESTURL\"}"
      }

resource:
  digitalocean_droplet:
    # this is the name of your VM
    do-instance:
      # and this is its identifier (required)
      name: 'koding-${var.koding_group_slug}-${var.koding_stack_id}-${count.index+1}'
      # select your instance_type here: eg. 512mb
      size: '512mb'
      # select your instance zone which must be in provided region: eg. nyc2
      region: 'nyc2'
      # base image for your droplet
      image: 'ubuntu-14-04-x64'
      # on user_data section we will write bash and configure our VM
      user_data: |-
        # clone repo based on the payload data:
        
        export PUBLICIP=`curl p.koding.com/-/ip`
        export REPO=${var.payload_repository_full_name}
        export APITOKEN=${var.custom_githubToken}
        export COMMIT_ID=${var.payload_after}
        export TESTURL=http://$PUBLICIP:3000
        
        # export helper for using with GitHub Status API
        ${var.github_status}
        
        GH_POST "pending"

        mkdir /code; cd /code
        apt-get update -y
        apt-get install git nodejs npm -y
        
        git clone ${var.payload_repository_url}
        cd ${var.payload_repository_name}
        git checkout ${var.payload_after}
        
        npm install
        npm start &
        
        
        echo "All Done!"
        echo "You can visit http://$PUBLICIP:3000 now!"
        
        GH_POST "success"
        
```

To make it work you need to provide `githubToken` as `Custom Variables` which only needs `repo:status` scope to work.

### CODE REVIEW

**Comment by rjeczalik** [comment]
Do we use the `Kloud.{add,unset,remove,set}Domain` and `Kloud.createSnapshot` methods anywhere? They're leftovers from solo, kloud does not support them anymore.

**Comment by gokmen** [comment]
> Do we use the Kloud.{add,unset,remove,set}Domain and Kloud.createSnapshot methods anywhere? They're leftovers from solo, kloud does not support them anymore.

I was going to ask for them 👍  they'll be removed.

**Review by cihangir — APPROVED** [review]
👍

**Review by rjeczalik — APPROVED** [review]

**Comment by gokmen** [comment]
test is failing due to missing `models.json` even though it's in place :( https://app.wercker.com/buildstep/58900a823253e401000435cf also didn't we disable this codecov report commenting if there is no coverage change introduced in PRs ?

**Review by szkl — APPROVED** [review]
:+1:

**Comment by szkl** [comment]
I've noticed the first error we've seen is actually [thrown](https://github.com/koding/koding/blob/master/node_modules_koding/bongo/lib/bongo.coffee#L228-L232) for any error.

I've enabled `debug` package in CI pipeline to see [actual](https://github.com/koding/koding/blob/master/node_modules_koding/bongo/lib/bongo.coffee#L225) error message.

```
$ scripts/wercker/run-command ./run exec scripts/api-generator.coffee --check
  bongo Model list found: /pipeline/build/workers/social/lib/social/models/models.json +0ms
  bongo Loading 52 models... +1ms
  bongo Loading model: JAccount +0ms
  bongo Loading model: JApiToken +1s
  bongo Loading model: Collaboration +659ms
  bongo Loading model: JCombinedAppStorage +1s
  bongo Loading model: ComputeProvider +1ms
  bongo Loading model: JCredential +285ms
  bongo Loading model: JCredentialData +780ms
  bongo Loading model: Kloud +1ms
  bongo Cache not found or corrupted, re-building... +133ms
  bongo Error was: unexpected = +0ms
```

I'm still investigating the root cause.

PS: File path is missing root components [intentionally](https://github.com/koding/koding/blob/master/node_modules_koding/bongo/lib/bongo.coffee#L207) in the initial error message.

**Comment by szkl** [comment]
Only difference between outputs of development and CI environment is the second line in the snippet below.

```
  bongo Loading model: Kloud +0ms
[kite] INFO     Trying to connect to http://localhost:80/kloud/kite
```

So, whatever is the "unexpected" error it is occurring before `Kite` instance opens a connection to `kloud` kite.

**Comment by gokmen** [comment]
@szkl I've fixed the issue at https://github.com/koding/koding/pull/10408/commits/6ae6e80e4e3d48f66ce671feb3f8f4c8ceaa623f#diff-a735c012c5b76ba49cf7ebb39e22af39R97 which is fine for coffee > 1.12.2 but it seems at that point global coffee-script version is different on wercker instance which is causing the issue. it was hard to find though :(

**Comment by szkl** [comment]
@gokmen 👏 I figured it'd be hard to be hard to find. Question is what is depending on global `coffee-script`?

**Comment by gokmen** [comment]
@szkl `api-generator --check`

**Pull request merged**
