### PR TITLE
More cleanup on client side

### LINKED ISSUE #10304: Remove unused static assets (images, etc) from client side

### PR DESCRIPTION
**Pull request by usirin**
- [x] Remove _more_ unused controllers
- [x] Remove _more_ unused KD views
- [x] Remove _more_ unused React components
- [x] Remove unused static assets (images) (fixes #10304)
  - [x] ~~```├── ace```~~ (no unused image)
  - [x] ```├── app```
  - [x] ~~```├── finder```~~ (no unused image)
  - [x] ```├── home```
  - [x] ```├── ide```
  - [x] ```└── stack-editor```
- [ ] Remove unused styles & identify and remove unused css classes.
  - [ ] make a final pass for unused assets again (some unused css classes use sprites, when they get obsolete, images will become obsolete as well)

Still in progress, trying to split up into multiple PRs makes things harder with no visible gain. I am trying to make my commits as clear as possible.

### CODE REVIEW

**Comment by usirin** [comment]
Till this commit, i am still removing unused & unbundled files to remove unnecessary noise. 

Furthermore i am planning to will include more investigated removals, such as identifying which css classes are not used, after that it will bring more assets that are not being used.

**Comment by usirin** [comment]
cc @koding/frontend

**Review by sinan — APPROVED** [review]

**Comment by usirin** [comment]
Cleanup for unused images in all apps are done, switching to css rules removals (thus any related assets).

**Comment by usirin** [comment]
@gokmen Do you know if we are still using `MissingDataView`? It's required in lots of places, and i didn't want to do any removal before talking to you.

**Review by gokmen — APPROVED** [review]

**Comment by usirin** [comment]
`resurrection.commons.styl` is cleared 🎊

**Comment by usirin** [comment]
`resurrection.sidebar.styl` is cleared 🎊

**Comment by usirin** [comment]
`resurrection.styl` is cleared 🎊

**Comment by usirin** [comment]
I think this PR is ready enough to be merged, What's left is `styl` files in folders other than `app/lib/styl` and the overall image cleanup, after all the unnecessary css rules are cleared.

/cc @gokmen @sinan

**Comment by sinan** [comment]
🥇 thx @usirin. Make sure the tests are passing and then we can take this in.

**Comment by gokmen** [comment]
I've restarted the tests, fyi.

**Comment by usirin** [comment]
Tests are green, merging.

**Pull request merged**
