### PR TITLE
Presence list members

### PR DESCRIPTION
**Pull request by mehmetalisavas**
### Request without logging in:
```
curl 'http://localhost:4480/api/social/presence/listmembers?skip=1&limit=1'
{"description":"not logged in","error":"koding.BadRequest"}
```
### Request/Response if user is not admin of the group:
```
curl --cookie 'clientId=384c1098-5e63-48cb-afa7-f2f733989862' 'http://localhost:4480/api/social/presence/listmembers?skip=1&limit=1'
{"description":"not admin of the group","error":"koding.BadRequest"}
```
### Request/Response if user is admin of the group:
```
curl --cookie 'clientId=7004d47d-03b7-4b01-9e1d-ddcaee55086b' 'http://localhost:4480/api/social/presence/listmembers?skip=1&limit=1'
{
   "accounts" : [
      {
         "globalFlags" : [],
         "_id" : "5852d6d3a54d75a64bd4f5a9",
         "meta" : {
            "likes" : 0,
            "modifiedAt" : "0001-01-01T00:00:00Z",
            "createdAt" : "0001-01-01T00:00:00Z"
         },
         "profile" : {
            "firstName" : "",
            "lastName" : "",
            "nickname" : "5852d6d3a54d75a64bd4f5a8",
            "hash" : ""
         },
         "isExempt" : false,
         "systemInfo" : {
            "defaultToLastUsedEnvironment" : false
         },
         "type" : "",
         "status" : "",
         "lastLoginTimezoneOffset" : 0,
         "socialApiId" : "34"
      }
   ],
   "deletedCount" : 0
}
```

### CODE REVIEW

**Comment by cihangir** [comment]
cc @usirin

**Review by cihangir — APPROVED** [review]

**Comment by usirin** [comment]
Good job! 👍 

How can i start using it once it's merged?

**Comment by cihangir** [comment]
@mehmetalisavas can you write a doc on how to use this feature? (with curl commands)

**Comment by mehmetalisavas** [comment]
@usirin usage is added with curl

**Pull request merged**
