### PR TITLE
terraformer: update state.tf on failure

### PR DESCRIPTION
**Pull request by rjeczalik**
ref: https://github.com/koding/koding/pull/8737#discussion_r74727593

### CODE REVIEW

**Comment by rjeczalik** [comment]
/cc @szkl - just fyi

i-4f1b21fa/cloud-init-output.log:

```
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! koding-client@0.1.0 preinstall: `./.npm-preinstall.sh`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the koding-client@0.1.0 preinstall script './.npm-preinstall.sh'.
```

**Comment by cihangir** [comment]
https://github.com/koding/koding/pull/8808#issuecomment-239796376 on a parallel universe sandbox and latest deploys failed on npm install today ( all 3 instances )

**Comment by szkl** [comment]
@rjeczalik do you have full logs?

**Comment by rjeczalik** [comment]
> @rjeczalik do you have full logs?

Sure thing sir, here you go - https://gist.github.com/rjeczalik/96b50db01674f175b29a0dfc192e24b5.

Fetched from kodingdev-test-instance-logs/57b1b407a6ab990100c2631e.

**Comment by szkl** [comment]
@cihangir it's usually binary for appmetrics package downloaded from somewhere else.

**Comment by rjeczalik** [comment]
@cihangir gentle ping

**Pull request merged**
