### PR TITLE
koding: switch to go1.6 / glide

### PR DESCRIPTION
**Pull request by rjeczalik**
PR split into second one containing only code changes for review purpose - https://github.com/koding/koding/pull/8616

Recreated after fork update - https://github.com/koding/koding/pull/8375

### CODE REVIEW

**Comment by cihangir** [comment]
👍 

Lets wait for our CI integration restoration

**Comment by rjeczalik** [comment]
Temporarily I could push to upstream/go1.6 to have the CI running. For now waiting for test-ami with go1.6.

**Comment by szkl** [comment]
Incoming! 💣💥

**Pull request closed without merging**
