### PR TITLE
Send stop/kill signal to process group

### PR DESCRIPTION
**Pull request by szkl**
Resolves https://github.com/koding/koding/issues/8666

Signed-off-by: Sonmez Kartal sonmez@koding.com

### CODE REVIEW

**Comment by szkl** [comment]
`stopasgroup` implies `killasgroup`.

**Comment by cihangir** [comment]
as you know i dont like implicity :)

**Comment by szkl** [comment]
Updated.

**Comment by cihangir** [comment]
Thanks sir!

**Pull request merged**
