### PR TITLE
Run development runtime in compose environment

### PR DESCRIPTION
**Pull request by szkl**
Resolves https://github.com/koding/koding/issues/8489

### CODE REVIEW

**Comment by gokmen** [comment]
didn't work me with the following error while building `landing`

```
backend_1   | make: Entering directory `/opt/koding/client'
backend_1   | make -C landing
backend_1   | make[1]: Entering directory `/opt/koding/client/landing'
backend_1   | [21:57:05] Requiring external module coffee-script/register
backend_1   | [21:57:05] Warning: gulp version mismatch:
backend_1   | [21:57:05] Global gulp is 3.9.1
backend_1   | [21:57:05] Local gulp is 3.9.0
backend_1   | [21:57:07] Using gulpfile /opt/koding/client/landing/gulpfile.coffee
backend_1   | [21:57:07] Starting 'build-all-sites'...
backend_1   | [21:57:08] Requiring external module coffee-script/register
backend_1   | [21:57:08] Working directory changed to /opt/koding/client/landing/site.landing
backend_1   | [21:57:12] Using gulpfile /opt/koding/client/landing/site.landing/gulpfile.coffee
backend_1   | [21:57:12] Starting 'libs'...
backend_1   | [21:57:12] Starting 'sprites@1x'...
backend_1   | [21:57:12] 'sprites@1x' errored after 733 μs
backend_1   | [21:57:12] Error: Cannot find module '/opt/koding/client/landing/../.config.json'
backend_1   |   at Function.Module._resolveFilename (module.js:338:15)
backend_1   |   at Function.Module._load (module.js:280:25)
backend_1   |   at Module.require (module.js:364:17)
backend_1   |   at require (module.js:380:17)
backend_1   |   at Object.module.exports (/opt/koding/client/landing/gulptasks/task.sprites.coffee:14:13)
backend_1   |   at module.exports (/opt/koding/client/landing/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
backend_1   |   at Gulp.Orchestrator._runTask (/opt/koding/client/landing/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
backend_1   |   at Gulp.Orchestrator._runStep (/opt/koding/client/landing/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
backend_1   |   at Gulp.Orchestrator.start (/opt/koding/client/landing/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
backend_1   |   at /opt/koding/client/landing/node_modules/gulp/bin/gulp.js:129:20
backend_1   |   at process._tickCallback (node.js:419:13)
backend_1   |   at Function.Module.runMain (module.js:499:11)
backend_1   |   at startup (node.js:119:16)
backend_1   |   at node.js:906:3
backend_1   | 
backend_1   | [21:57:12] Finished 'libs' after 33 ms
backend_1   | [21:57:12] 'build-all-sites' errored after 5.62 s
backend_1   | [21:57:12] Error in plugin 'gulp-shell'
backend_1   | Message:
backend_1   |     Command `gulp --gulpfile ./site.landing/gulpfile.coffee build --uglify` failed with exit code 1
backend_1   | make[1]: *** [all] Error 1
backend_1   | make[1]: Leaving directory `/opt/koding/client/landing'
backend_1   | make: *** [landing] Error 2
backend_1   | make: Leaving directory `/opt/koding/client'
```

**Comment by szkl** [comment]
Actual error is configure script failing to clone vault because it assumes `dev` environment. I'm looking into it right now.

**Comment by szkl** [comment]
Updated. Please, test this first if you can.

**Comment by gokmen** [comment]
@szkl works well for me

**Pull request merged**
