### PR TITLE
Design Update for Expanded VM list 

### PR DESCRIPTION
**Pull request by hakankaradis**
Update edit machine name feature in Virtual Machines section.
## Description
- [x] Add edit VM name section to machine details section
- [x] remove padding for build logs
- [x] update machine header style
- [x] add header-line for machine-specs
- [x] button and toggles css updated
## Motivation and Context
#9104
## How Has This Been Tested?

Manually
## Screenshots (if appropriate):

http://recordit.co/Yl2DkjQWss
http://recordit.co/XIq8xJqyAo
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by hakankaradis** [comment]
http://recordit.co/609pbPvGAU
@sinan updated

**Comment by gokmen** [comment]
@hakankaradis let's keep that textbox with in row boundaries, this space is not required on edit mode;
image

it shouldn't change any other item's position when edit mode toggled.

**Review by sinan — CHANGES_REQUESTED** [review]
code is looking good, if you can fix @gokmen's comment with @ftasdelen we can take this in.

**Comment by hakankaradis** [comment]
http://recordit.co/NQCgnSKSeS
@sinan updated

**Review by sinan — APPROVED** [review]

**Pull request merged**
