### PR TITLE
Finish Pricing

### PR DESCRIPTION
**Pull request by usirin**
- [x] don't require email/name when entering a credit card
- [x] show a modal to the first logged in ~~member~~ **admin** for an existing group indicating that we changed pricing terms.
- [x] automatically start a subscription no matter if first logged in user is member or admin.
- [x] make sure congrats modal only shows up on successful credit card entries.
### Modal showing up for first logged in member:

image

/cc @cihangir @sibblegp

### CODE REVIEW

**Review by gokmen — APPROVED** [review]

**Comment by gokmen** [comment]
LGTM restarted tests, will be merged once tests passed!

**Comment by usirin** [comment]
Green!

**Comment by usirin** [comment]
@sinan updated with the requested changes.

**Review by gokmen — APPROVED** [review]

**Review by sinan — APPROVED** [review]
👍

**Pull request merged**
