### PR TITLE
client: add spaces between progress bar and tags

### LINKED ISSUE #9061: There should be some space between progress bar and the tags
## Current Behavior
image

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37969452-there-should-be-some-space-between-progress-bar-and-the-tags?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cansirin**
## Description

Currently, there was no space between progress bar and tags, this PR adds space between bar and tags.
## Motivation and Context

Fixes #9061 
## How Has This Been Tested?

Manually
## Screenshots (if appropriate):

image
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by gokmen** [comment]
not directly related with this one but I'm also having issues with the spacing of label itself;

image

cc/ @ftasdelen @sinan

**Comment by sinan** [comment]
I was going to suggest a similar thing, @ftasdelen can you please make an iteration for all states of this component, so that we shouldn't break sth while fixing another.

**Comment by gokmen** [comment]
@cansirin merged this one, we can look at the other issue once we hear back from @ftasdelen

**Comment by cansirin** [comment]
Okay, thank you @gokmen. I'll make other issue is done when I hear from @ftasdelen

**Comment by ftasdelen** [comment]
What about this view?

@sinan @gokmen 
screen shot 2016-09-22 at 2 10 34 pm

**Comment by ftasdelen** [comment]
Updated the glitches out there.

image

image

**Comment by ftasdelen** [comment]
Here is the PDF file:

[VM List Update.pdf](https://github.com/koding/koding/files/488422/VM.List.Update.pdf)

**Comment by ftasdelen** [comment]
Updated PDF is here:

[VM List Update.pdf](https://github.com/koding/koding/files/488516/VM.List.Update.pdf)

**Comment by hakankaradis** [comment]
#9104

**Pull request merged**
