### PR TITLE
remoteapi: add swagger-generated client

### PR DESCRIPTION
**Pull request by rjeczalik**

### CODE REVIEW

**Comment by cihangir** [comment]
it seems we need a better swagger configuration, the current state wont be a good helper

**Review by cihangir — APPROVED** [review]

**Comment by rjeczalik** [comment]
> it seems we need a better swagger configuration, the current state wont be a good helper

You mean missing `BodyMeta` type?

**Review by ppknap — APPROVED** [review]

**Comment by cihangir** [comment]
I dont think this will affect anything on the tests, merging.

**Comment by cihangir** [comment]
re: https://github.com/koding/koding/pull/9824#issuecomment-263810175 yes

**Pull request merged**
