### PR TITLE
added analytics events list

### PR DESCRIPTION
**Pull request by sinan**
added a reference for the listened events

### CODE REVIEW

**Comment by cihangir** [comment]
```
2.591993ms trial started
2.591995ms trial started
2.591998ms trial started
2.591999ms trial started
createworkspace
enrichment_provider
received 1st VM deletion warning
received 2nd VM deletion warning
received a refuned
```

these are obsolete

**Comment by rjeczalik** [comment]
Also the following ones are obsolete as well:

```
+ - attempted to repair machine
+ - failed to repair machine
```

IIRC @ppknap removed that code from kd.

**Comment by ppknap** [comment]
> IIRC @ppknap removed that code from kd.

Yes, the major part of this command was about old mounts - not used anymore. Rest is either unrecoverable failures (klient is offline) or can be fixed by restarting the klient

**Comment by sinan** [comment]
removed all obsolete events.

**Review by cihangir — APPROVED** [review]

**Pull request merged**
