### PR TITLE
Interim stack editor

### PR DESCRIPTION
**Pull request by sinan**
This is an interim fix in an attempt to make the editor more usable, until we have the new design and functionality ready.

image

### CODE REVIEW

**Comment by hakankaradis** [comment]
screencapture-oct23-dev-koding-8090-stack-editor-5835f287bec5205c0a2bc5df-1479975880476

**Comment by sinan** [comment]
👍 approved @hakankaradis's changes.

**Review by gokmen — APPROVED** [review]

**Comment by gokmen** [comment]
it LGTM but let's wait next production deploy before merging this in since it will break some tests.

**Comment by sinan** [comment]
We just changed styling not to break tests, I think it's harmless.

**Comment by gokmen** [comment]
It breaks all rainforest tests.

**Comment by devrim** [comment]
we will re-write those RF tests - can you point to which ones?

**Comment by gokmen** [comment]
starting with this one https://github.com/koding/koding/blob/c47c04a56cc95dfae55ff1dec2ee8699948164c8/tests/spec/rainforest/clone_stack_template.rfml any file here https://github.com/koding/koding/tree/c47c04a56cc95dfae55ff1dec2ee8699948164c8/tests/spec/rainforest has stack in filename also can fail, QA needs to pass over these I believe. But if this is really urgent **but really urgent** we can merge it and made it ready for deploy.

**Pull request merged**
