### PR TITLE
Check remote API consistency in Circle CI build stage

### PR DESCRIPTION
**Pull request by szkl**
Signed-off-by: Sonmez Kartal <sonmez@koding.com>

### CODE REVIEW

**Comment by cihangir** [comment]
i dont know why remote-api-consistency checker requires redis connection

**Comment by gokmen** [comment]
> i dont know why remote-api-consistency checker requires redis connection
it shouldn't but Bongo might need it to get ready

**Comment by szkl** [comment]
Yes. Bongo needs redis.

**Comment by szkl** [comment]
Updated.

**Review by cihangir — APPROVED** [review]

**Pull request merged**
