### PR TITLE
Changed styles for landing page

### PR DESCRIPTION
**Pull request by drewsetski**

### CODE REVIEW

**Comment by gokmen** [comment]
Can u provide before/after screenshots for each visual change proposed in this PR? Thanks.

**Comment by drewsetski** [comment]
screencapture-localhost-4000-1492006702360
screencapture-localhost-4000-blog-1492007244168
screencapture-localhost-4000-about-1492006974968
screencapture-localhost-4000-pricing-1492006762106
screencapture-localhost-4000-features-1492006735021

**Comment by drewsetski** [comment]
[blog](https://cloud.githubusercontent.com/assets/7559232/24965152/ee31561c-1fab-11e7-8c77-cb448ca0cbe1.jpg)
[home](https://cloud.githubusercontent.com/assets/7559232/24965153/ee3391ca-1fab-11e7-9c4f-3d0e6047e340.jpg)
[about](https://cloud.githubusercontent.com/assets/7559232/24965154/ee3541aa-1fab-11e7-88e3-c1e4e3083f7e.jpg)
[pricing](https://cloud.githubusercontent.com/assets/7559232/24965156/ee42ac3c-1fab-11e7-87c6-f07601898179.jpg)
[features](https://cloud.githubusercontent.com/assets/7559232/24965155/ee35eb1e-1fab-11e7-8be6-b6df453ef00e.jpg)

**Comment by ftasdelen** [comment]
Hi.
There are some points needs attention and changes I listed below.

All Pages: 
- The triangular overlay on the header section should be aligned to the bottom of the container.

Pricing Page:
- Font update necessary for the headlines of the plan containers.

Features Page:
- Headline background gradient should be reverse. Dark side at the bottom.
- The first section should have been removed. "Flawless Replica..." section.
- On the second section, the layout is different and the logos must be  updated.
- "Seamless Support..." section layout and logos must be updated.
- "You Don;t need to change..." section: background color of right side of container should be updated.
- At the last section, "SSH and Sudo.." is not aligned to other two text blocks on the left. 

If you need further explanation, please let me or @hakankaradis know.

Thanks.

**Comment by sinan** [comment]
@ftasdelen we also need to remove the non-working parts from the features page.

**Comment by drewsetski** [comment]
Hello! I've fixed all issues and added code-example component. Services is carousel, so user can click on service and it will be centered.
### Data for the services is in `_data\services.yml` with such structure (example):
```
- name: Microsoft Azure
  image: logo_azure.svg
  width: 190
  height: 27
  active: true
  code: "aws_instances:	&#10;
        &nbsp;'App':&#10;
        &nbsp;&nbsp;instance_type: 'micro'&#10;
        &nbsp;&nbsp;ami: ''&#10;
        &nbsp;&nbsp;exec:&#10;
        &nbsp;&nbsp;&nbsp;apt-get install ruby mysql&#10;
        &nbsp;&nbsp;&nbsp;git clone git@github.com/koding/project.git&#10;
        &nbsp;&nbsp;&nbsp;chef-solo -c solo.rb -j web.json"
```

### Screenshot - [Features](https://cloud.githubusercontent.com/assets/7559232/25200615/a4675cd2-2557-11e7-9405-ede7a3a5d02c.png)

**Comment by hakankaradis** [comment]
closing this pr, it is reopened here #11017

**Pull request closed without merging**
