### PR TITLE
Algolia account deleter

### PR DESCRIPTION
**Pull request by mehmetalisavas**
Clean up algolia data that belongs to non existing accounts in mongo

### CODE REVIEW

**Comment by mehmetalisavas** [comment]
@cihangir PTAL

**Comment by cihangir** [comment]
you already deleted all the non existing accounts right?

**Review by cihangir — APPROVED** [review]
there are some things to comment in this PR but it is one-off script, we should clean them all at some point ~ 3-4 months later?

**Comment by mehmetalisavas** [comment]
@cihangir we've cleaned existing accounts and indexes on algolia.

**Pull request merged**
