### PR TITLE
kloud: fix user-data interpolations

### PR DESCRIPTION
**Pull request by rjeczalik**
Broken by:

```
d0f097d
```

Fixes:

```
[10:36:52] Starting to process the template...
[10:36:52] Something went wrong with the template:
[10:36:52] Cloudinit template is not a valid YAML file. Debugfile:
/tmp/kloud-cloudinit539095275 (error code: 900)
[10:36:52] Parsing failed, please check your template and try again
```

### CODE REVIEW

**Comment by cansirin** [comment]
Thank you @rjeczalik :)

**Comment by hakankaradis** [comment]
I pulled the master, but I am having the same problem
@rjeczalik

**Comment by rjeczalik** [comment]
@hakankaradis Are you sure e.g. there's no old kloud process running? I've tried the master now again and it's ok.

**Comment by hakankaradis** [comment]
@rjeczalik it is weird. I did nothing but it works right now. Thanks

**Pull request merged**
