### PR TITLE
third-party: update koding/terraform

### PR DESCRIPTION
**Pull request by rjeczalik**

### CODE REVIEW

**Comment by cihangir** [comment]
is it from https://github.com/koding/terraform or hashicorp/terraform?

**Comment by rjeczalik** [comment]
Still from github.com/koding/terraform - it contains a change that our frontend relies on (removed retries). If that behaviour is kept using upstream only, we could get rid of a fork.

**Comment by cihangir** [comment]
i asked because title was saying from hashicorp/terraform instead of koding/terraform,  updated it.

**Comment by rjeczalik** [comment]
:+1: Thanks!

**Pull request merged**
