### PR TITLE
Azure guide

### PR DESCRIPTION
**Pull request by kwagdy**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sinan — CHANGES_REQUESTED** [review]
thx @kwagdy the changes look good, however the product screenshots should have related details.
img

- [ ] find a dummy team name which looks like dummy. e.g. acme, pied-piper, myteam etc
- [ ] have a good looking logo for that dummy team @ftasdelen can help you with that.
- [x] make sure usernames look like usernames

**Comment by ftasdelen** [comment]
default team logo
default team logo 2x

We can use default team logo.

**Comment by kwagdy** [comment]
@sinan @ftasdelen I should note that I used the same team in all docs!

**Comment by kwagdy** [comment]
changed the team logo to this 
image

**Comment by kwagdy** [comment]
Can we merge this and I will need to go through all the docs screenshot again later?

**Review by sinan — APPROVED** [review]

**Pull request merged**
