### PR TITLE
Add IntegrationTestManager

### PR DESCRIPTION
**Pull request by anonrig**
WIP.

Just a heads up to the implementation of integration test manager.

/cc @devrim

### CODE REVIEW

**Comment by anonrig** [comment]
Scenario

http://recordit.co/zKBCmrbSp3

**Review by szkl — APPROVED** [review]

**Comment by anonrig** [comment]
Example output of the generator to convert Rainforest tests to Mocha tests. /cc @devrim 

image

**Comment by szkl** [comment]
@hakankaradis what's the status on this?

**Comment by hakankaradis** [comment]
@szkl I opened pull request for this https://github.com/koding/koding/pull/9884 already but I decided to not use socket for that implementation, we will use iframes, all tests will run in the same window. so still working on it.

**Pull request closed without merging**
