### PR TITLE
kloud/queue: fix fetching creds from socialapi

### PR DESCRIPTION
**Pull request by rjeczalik**

### CODE REVIEW

**Comment by cihangir** [comment]
👍

**Comment by rjeczalik** [comment]
@cihangir oh I changed it to wip, since there's one part missing with creating an user for kloud to communicate with socialapi - I'll send it separately

**Comment by cihangir** [comment]
sorry i didnt realize it was wip, code was OK. we can revert if you want?

**Comment by rjeczalik** [comment]
@cihangir There are two problems with #8630:

1) a username is not sent in request to socialapi
2)  there is was no kloud user to talk with socialapi

This PR fixes 1) so it's ok to have it merged. I can send 2) separately.

**Pull request merged**
