### PR TITLE
Tests parallelization

### PR DESCRIPTION
**Pull request by mehmetalisavas**

### CODE REVIEW

**Comment by ppknap** [comment]
@mehmetalisavas regarding these test failures: https://github.com/koding/koding/blob/master/go/src/koding/kites/config/config_test.go#L84

**Comment by mehmetalisavas** [comment]
@ppknap i will add parallelization to all tests if its possible. (i didn't read that comment :) )

**Review by cihangir — APPROVED** [review]

**Comment by mehmetalisavas** [comment]
PTAL

**Review by ppknap — APPROVED** [review]

**Review by rjeczalik — APPROVED** [review]

**Comment by cihangir** [comment]
Everyone has approved this PR, merging.

**Pull request merged**
