### PR TITLE
Set version option to `master`

### PR DESCRIPTION
**Pull request by szkl**
Signed-off-by: Sonmez Kartal <sonmez@koding.com>

### CODE REVIEW

**Comment by cihangir** [comment]
would you mind explaining why we need this?

**Comment by szkl** [comment]
configure script fallbacks to default 1.0 as version which is misrepresented (as 1) in some places. git revision is not available because .git directory is not available in the context. I've thought setting a predefined version would prevent mishandling of version option.

**Comment by cihangir** [comment]
got it. this wont break the build command right? https://github.com/koding/koding-gitlab/blob/master/koding/deployment.yaml#L23-L24

**Comment by szkl** [comment]
Nope. It will overwrite version as it is right now 👍

**Review by cihangir — APPROVED** [review]

**Pull request merged**
