### PR TITLE
'Stack Updated' notification jewel is overlapping with the stack menu down arrow. 

### PR DESCRIPTION
**Pull request by hakankaradis**
Stack Updated notification jewel is overlapped by menu drop down arrow
## Motivation and Context
#8857
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sinan** [comment]
please make all the hover items visible on whole sidebar and share a screenshot so that I can approve this.

**Comment by hakankaradis** [comment]
@sinan

**Comment by sinan** [comment]
one last iteration pls 😏 
img

**Comment by hakankaradis** [comment]
@sinan updated

**Comment by sinan** [comment]
👍

**Pull request merged**
