### PR TITLE
ResourceStateModal: build stack success view update

### PR DESCRIPTION
**Pull request by alex-ionochkin**
This PR contains design and functionality changes on build stack success view. See linked issue as a a reference for design screenshots
## Motivation and Context

https://github.com/koding/koding/issues/9159
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by gokmen — APPROVED** [review]

**Comment by gokmen** [comment]
@alex-ionochkin can u check tests?

**Comment by alex-ionochkin** [comment]
@gokmen, all tests are passed now. Rebase has fixed tests issue

**Comment by ftasdelen** [comment]
@alex-ionochkin can we show this tooltip when user clicks "Invite" button and the collaboration progress bar started?

image

Thanks.

You can see the whole flow on this pdf:
[new stack modal new success modal.pdf](https://github.com/koding/koding/files/534336/new.stack.modal.new.success.modal.pdf)

**Comment by gokmen** [comment]
@ftasdelen we can do this change on further iterations, merging this for now. cc/ @alex-ionochkin

**Comment by ftasdelen** [comment]
@gokmen Sure. Other than that, LGTM.

**Pull request merged**
