### PR TITLE
klientctl: create kd command structure for cobra CLI 

### PR DESCRIPTION
**Pull request by ppknap**
⚠️ This PR is large, however all the files it contains have a similar structure. The goal is to check if all commands have proper description, flags, and requirements. The best way to do so is to compare each command with `main.go`. Number of accepted arguments should not be checked (currently it is set to `NoArgs` for all commands) ⚠️ 

Commands implementation will be done in a separate PR.

## Description
Each file contains a full description of the command and middlewares it takes. There is also a hidden `kd cli` subcommand that allows analyzing applied middlewares: 

<details>

```json
{
	"daemon_required": [
		"kd auth",
		"kd auth login",
		"kd auth register",
		"kd auth show",
		"kd bug",
		"kd cp",
		"kd credential create",
		"kd credential describe",
		"kd credential init",
		"kd credential list",
		"kd credential use",
		"kd daemon restart",
		"kd daemon start",
		"kd daemon stop",
		"kd daemon update",
		"kd exec",
		"kd init",
		"kd list",
		"kd machine config set",
		"kd machine config show",
		"kd machine cp",
		"kd machine exec",
		"kd machine list",
		"kd machine mount",
		"kd machine mount inspect",
		"kd machine mount list",
		"kd machine mount sync",
		"kd machine mount sync pause",
		"kd machine mount sync resume",
		"kd machine ssh",
		"kd machine start",
		"kd machine stop",
		"kd machine umount",
		"kd metrics",
		"kd metrics add",
		"kd mount",
		"kd mount inspect",
		"kd mount list",
		"kd mount sync",
		"kd mount sync pause",
		"kd mount sync resume",
		"kd open",
		"kd restart",
		"kd ssh",
		"kd stack create",
		"kd stack list",
		"kd start",
		"kd status",
		"kd stop",
		"kd sync",
		"kd sync pause",
		"kd sync resume",
		"kd team list",
		"kd team show",
		"kd team use",
		"kd team whoami",
		"kd template delete",
		"kd template init",
		"kd template list",
		"kd template show",
		"kd umount",
		"kd update"
	],
	"initialized_cache": [
		"kd",
		"kd auth",
		"kd auth login",
		"kd auth register",
		"kd auth show",
		"kd bug",
		"kd cli",
		"kd config",
		"kd config list",
		"kd config reset",
		"kd config set",
		"kd config show",
		"kd config unset",
		"kd config use",
		"kd cp",
		"kd credential",
		"kd credential create",
		"kd credential describe",
		"kd credential init",
		"kd credential list",
		"kd credential use",
		"kd daemon",
		"kd daemon install",
		"kd daemon restart",
		"kd daemon start",
		"kd daemon stop",
		"kd daemon uninstall",
		"kd daemon update",
		"kd exec",
		"kd init",
		"kd install",
		"kd list",
		"kd log",
		"kd log upload",
		"kd machine",
		"kd machine config",
		"kd machine config set",
		"kd machine config show",
		"kd machine cp",
		"kd machine exec",
		"kd machine list",
		"kd machine mount",
		"kd machine mount inspect",
		"kd machine mount list",
		"kd machine mount sync",
		"kd machine mount sync pause",
		"kd machine mount sync resume",
		"kd machine ssh",
		"kd machine start",
		"kd machine stop",
		"kd machine umount",
		"kd metrics",
		"kd metrics add",
		"kd mount",
		"kd mount inspect",
		"kd mount list",
		"kd mount sync",
		"kd mount sync pause",
		"kd mount sync resume",
		"kd open",
		"kd restart",
		"kd ssh",
		"kd stack",
		"kd stack create",
		"kd stack list",
		"kd start",
		"kd status",
		"kd stop",
		"kd sync",
		"kd sync pause",
		"kd sync resume",
		"kd team",
		"kd team list",
		"kd team show",
		"kd team use",
		"kd team whoami",
		"kd template",
		"kd template delete",
		"kd template init",
		"kd template list",
		"kd template show",
		"kd umount",
		"kd uninstall",
		"kd update",
		"kd version"
	],
	"sudo_required": [
		"kd daemon install",
		"kd daemon restart",
		"kd daemon start",
		"kd daemon stop",
		"kd daemon uninstall",
		"kd daemon update",
		"kd install",
		"kd restart",
		"kd start",
		"kd stop",
		"kd uninstall",
		"kd update"
	],
	"with_metrics": [
		"kd auth login",
		"kd auth register",
		"kd auth show",
		"kd bug",
		"kd config list",
		"kd config reset",
		"kd config set",
		"kd config show",
		"kd config unset",
		"kd config use",
		"kd cp (alias: kd machine cp)",
		"kd credential create",
		"kd credential describe",
		"kd credential init",
		"kd credential list",
		"kd credential use",
		"kd daemon install",
		"kd daemon restart",
		"kd daemon start",
		"kd daemon stop",
		"kd daemon uninstall",
		"kd daemon update",
		"kd exec (alias: kd machine exec)",
		"kd init",
		"kd install (alias: kd daemon install)",
		"kd list (alias: kd machine list)",
		"kd log upload",
		"kd machine config set",
		"kd machine config show",
		"kd machine cp",
		"kd machine exec",
		"kd machine list",
		"kd machine mount",
		"kd machine mount inspect",
		"kd machine mount list",
		"kd machine mount sync",
		"kd machine mount sync pause",
		"kd machine mount sync resume",
		"kd machine ssh",
		"kd machine start",
		"kd machine stop",
		"kd machine umount",
		"kd mount (alias: kd machine mount)",
		"kd mount inspect (alias: kd machine mount inspect)",
		"kd mount list (alias: kd machine mount list)",
		"kd mount sync (alias: kd machine mount sync)",
		"kd mount sync pause (alias: kd machine mount sync pause)",
		"kd mount sync resume (alias: kd machine mount sync resume)",
		"kd open",
		"kd restart (alias: kd daemon restart)",
		"kd ssh (alias: kd machine ssh)",
		"kd stack create",
		"kd stack list",
		"kd start (alias: kd daemon start)",
		"kd stop (alias: kd daemon stop)",
		"kd sync (alias: kd machine mount sync)",
		"kd sync pause (alias: kd machine mount sync pause)",
		"kd sync resume (alias: kd machine mount sync resume)",
		"kd team list",
		"kd team show",
		"kd team use",
		"kd team whoami",
		"kd template delete",
		"kd template init",
		"kd template list",
		"kd template show",
		"kd umount (alias: kd machine umount)",
		"kd uninstall (alias: kd daemon uninstall)",
		"kd update (alias: kd daemon update)"
	]
}
```
</details>

## Motivation and Context
Migration to `cobra`

## How Has This Been Tested?
Manually.

### CODE REVIEW

**Review by rjeczalik — APPROVED** [review]

**Comment by cihangir** [comment]
Instead of adding "cli.WithMetrics(aliasPath...)" to every command manually in the command functions, could we insert the metrics automatically (like we had previously)? That way we wont forget to add metrics onto commands?

**Review by cihangir — APPROVED** [review]

**Comment by ppknap** [comment]
@cihangir we can use `cli.ApplyForAll` like it is done [here](https://github.com/koding/koding/blob/040b0bbe0c2f24ef724680297589314a8639619c/go/src/koding/klientctl/commands/kd.go#L71). I explicitely added metrics to commands because I'm not sure if we want them for *all* commands. Let me give some examples:

 - `kd version` - I'm not sure if metrics for this command are of any use.
 - `kd status` - this may be called quite frequently by tools which use kd and probably have no meaningful information.
 - `kd machine`, `kd daemon`, `kd config` etc. - these commands do nothing. They only print help information. However, if we use `ApplyForAll` they will be count by DataDog.

We can overcome the third bullet, but not sure if this is worth the effort. We don't add new commands frequently (and we may not want to measure all of them).

Also, we have hidden `kd cli` command that displays which commands are measured - sample output is in PR's description.

**Comment by rjeczalik** [comment]
We could add some bool field or wrapper type that would basically say "skip me" when processed by ApplyForAll. Just an idea.

**Comment by ppknap** [comment]
yeah, that's why I wrote: `We can overcome the third bullet,...` :) . The question is: Is it worth the effort since we still need to remember about skipping/not skipping the metrics?

Moreover, at this moment wrappers have no idea what they wrap. With `skip me` they will have to know that they must skip only metrics wrapper but not eg. cache one. I can compare this to a base class which must depend on the type of delivered class.

**Comment by cihangir** [comment]
> Is it worth the effort

I believe the current approach takes more effort than wrapping everything. 

> probably have no meaningful information.

I dont agree. ie: If we see a huge number of "kd machine" usage in metrics we could infer that folks want to use their machines but they dont know how to. <- applies to "version" command as well.

my motto on observability is 

"collecting data is cheap, but not having it when you need it can be expensive" - famous guys from the internet

**Comment by ppknap** [comment]
> I believe the current approach takes more effort than wrapping everything.

So, are you in favor of putting metrics for *all* commands recursively [here](https://github.com/koding/koding/blob/040b0bbe0c2f24ef724680297589314a8639619c/go/src/koding/klientctl/commands/kd.go#L70)? If yes, it's easy to change. Will do this in future PRs before switching old logic.

> "collecting data is cheap, but not having it when you need it can be expensive"

Agree! However, I was speaking of false positive results: if some tool frequently pools `kd status`, we will not know if this was a user who really wants to find the status of kd or just eg. `Atom` editor left open for a night. This makes these statistics meaningless - at least for me:)

**Comment by cihangir** [comment]
> So, are you in favor of putting metrics for all commands

yep

> we will not know if this was a user who really wants ....


On the other hand, we will know there is something that abuses the "kd status" command and would take preventive actions on that (ie create another subcommand for that "abuser"), if we dont keep metrics we wont know "X is abusing `kd status`"

**Pull request merged**
