### PR TITLE
Update time attributes of files restored from cache

### PR DESCRIPTION
**Pull request by szkl**
Signed-off-by: Sonmez Kartal <sonmez@koding.com>

### CODE REVIEW

**Review by rjeczalik — APPROVED** [review]

**Review by cihangir — APPROVED** [review]

**Comment by cihangir** [comment]
why is this required?

**Comment by rjeczalik** [comment]
Circle caches pkg/ and bin/,  once unzipped go rebuilds them either way
since source tree has mtime > the archived ones.

**Comment by cihangir** [comment]
I see go build run again for this PR, could we say that does not solve the rebuilding issue?

**Comment by rjeczalik** [comment]
Maybe there's issue with caching? (e.g. single cache file and some feature
brach overwrites it?)

**Comment by szkl** [comment]
@cihangir you're right. There are still some packages rebuilt. I've one more idea to try which might make this pull request obsolete. However, this change helps with the excessive memory allocation by the build process. It can be evaluated as a band-aid to achieve ✅  in the CI.

**Comment by cihangir** [comment]
@rjeczalik i was assuming it was always the cache being an issue from the beginning 

> There are still some packages rebuilt.

@szkl what about running that command under src folder too? if the issue is 

> mtime > the archived ones.

it is worth trying

**Comment by szkl** [comment]
🏁

**Review by cihangir — APPROVED** [review]

**Pull request merged**
